type User {
  id: ID!
  name: String!
  avatar: String
  email: String!
  notes: [Note!]!
}

type Note {
  id: ID!
  title: String!
  description: String
  color: String!
  author: User!
  archived: Boolean
}

type Query {
  notes(authorId: ID!): [Note!]!
  note(id: ID!): Note!
  author(id: ID!): User!
}

input NoteData {
  title: String!
  description: String
  color: String!
  authorId: String!
}

type NoteId {
  id: ID!
}

type Mutation {
  addNote(data: NoteData!): Note!
  deleteNote(id: ID!): NoteId!
  archiveNote(id: ID!): NoteId!
  unarchiveNote(id: ID!): NoteId!
}
