type Author {
  id: ID!
  name: String!
  avatar: String
  email: String!
  notes: [Note!]!
}

type Note {
  id: ID!
  title: String!
  description: String
  color: String!
  author: Author!
}

type Query {
  notes(authorId: ID!): [Note!]!
  note(id: ID!): Note!
  author(id: ID!): Author!
}

input NoteData {
  title: String!
  description: String
  color: String!
  authorId: String!
}

type Mutation {
  addNote(data: NoteData!): Note!
}
